/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.isw.pruebassoftware.app.recetas.cocina.uc1;

/**
 *
 * @author Dell
 */
public class DlgIngredientesReceta extends javax.swing.JDialog {
    
    /**
     * Creates new form DlgIngredientesReceta
     */
    public DlgIngredientesReceta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreReceta = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtTipoDeCocina = new javax.swing.JTextField();
        lblIngredientes = new javax.swing.JLabel();
        lblPasos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreReceta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 32)); // NOI18N
        lblNombreReceta.setText("Informacion");
        jPanel1.add(lblNombreReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 560, 80));

        btnRegresar.setBackground(new java.awt.Color(92, 157, 157));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, 70));

        txtNombre.setBackground(new java.awt.Color(211, 204, 192));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 400, 60));

        txtTipoDeCocina.setBackground(new java.awt.Color(211, 204, 192));
        txtTipoDeCocina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtTipoDeCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 510, 60));

        lblIngredientes.setText("Ingredientes:");
        getContentPane().add(lblIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        lblPasos.setText("Pasos:");
        getContentPane().add(lblPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IngredientesReceta.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblNombreReceta;
    private javax.swing.JLabel lblPasos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoDeCocina;
    // End of variables declaration//GEN-END:variables
}
