/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.isw.pruebassoftware.app.recetas.cocina.uc1;

/**
 *
 * @author Dell
 */
public class DlgListaIngredientes extends javax.swing.JDialog {

    /**
     * Creates new form DlgListaIngredientes
     */
    public DlgListaIngredientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaIngredientes = new javax.swing.JTable();
        btnVaciarLista = new javax.swing.JButton();
        btnIngredientesPorReceta = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1499, 854));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListaIngredientes.setBackground(new java.awt.Color(217, 217, 217));
        tblListaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaIngredientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1440, 600));

        btnVaciarLista.setBackground(new java.awt.Color(92, 157, 157));
        btnVaciarLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVaciarLista.setText("Vaciar lista");
        btnVaciarLista.setBorder(null);
        btnVaciarLista.setBorderPainted(false);
        getContentPane().add(btnVaciarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 760, 230, 60));

        btnIngredientesPorReceta.setBackground(new java.awt.Color(92, 157, 157));
        btnIngredientesPorReceta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIngredientesPorReceta.setText("Ingredientes por receta");
        btnIngredientesPorReceta.setBorder(null);
        btnIngredientesPorReceta.setBorderPainted(false);
        getContentPane().add(btnIngredientesPorReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 763, 440, 60));

        btnRegresar1.setBackground(new java.awt.Color(92, 157, 157));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar1.setText("Regresar");
        btnRegresar1.setBorder(null);
        btnRegresar1.setBorderPainted(false);
        getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 760, 230, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listaIngredientes.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1772, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgListaIngredientes dialog = new DlgListaIngredientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngredientesPorReceta;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnVaciarLista;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaIngredientes;
    // End of variables declaration//GEN-END:variables
}
