/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.isw.pruebassoftware.app.recetas.cocina.uc1;

/**
 *
 * @author Jesus
 */
public class DlgMenuUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DlgMenuUsuario
     */
    public DlgMenuUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarEnMenu = new javax.swing.JButton();
        btnGuardados = new javax.swing.JButton();
        btnListaCompraIngredientes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarEnMenu.setBackground(new java.awt.Color(92, 157, 157));
        btnBuscarEnMenu.setFont(new java.awt.Font("Segoe UI Emoji", 1, 32)); // NOI18N
        btnBuscarEnMenu.setText("Explorar menú");
        btnBuscarEnMenu.setBorderPainted(false);
        btnBuscarEnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarEnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 212, 544, 75));

        btnGuardados.setBackground(new java.awt.Color(92, 157, 157));
        btnGuardados.setFont(new java.awt.Font("Segoe UI Emoji", 1, 32)); // NOI18N
        btnGuardados.setText("Platillos guardados");
        btnGuardados.setBorderPainted(false);
        getContentPane().add(btnGuardados, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 338, 544, 75));

        btnListaCompraIngredientes.setBackground(new java.awt.Color(92, 157, 157));
        btnListaCompraIngredientes.setFont(new java.awt.Font("Segoe UI Emoji", 1, 32)); // NOI18N
        btnListaCompraIngredientes.setText("Lista de ingredientes");
        btnListaCompraIngredientes.setBorderPainted(false);
        getContentPane().add(btnListaCompraIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 464, 544, 75));

        btnCerrarSesion.setBackground(new java.awt.Color(92, 157, 157));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 32)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 600, 544, 75));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUsuario.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEnMenuActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEnMenu;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGuardados;
    private javax.swing.JButton btnListaCompraIngredientes;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
