/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.isw.pruebassoftware.app.recetas.cocina.uc1;

/**
 *
 * @author Jesus
 */
public class DlgMenuPlatillos extends javax.swing.JDialog {

    /**
     * Creates new form DlgMenuPlatillos
     */
    public DlgMenuPlatillos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        txtIngredienteF = new javax.swing.JTextField();
        txtTipoCocina = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlatillos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(92, 157, 157));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 32)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, 191, 50));

        txtIngredienteF.setBackground(new java.awt.Color(212, 199, 199));
        txtIngredienteF.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtIngredienteF.setBorder(null);
        txtIngredienteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteFActionPerformed(evt);
            }
        });
        getContentPane().add(txtIngredienteF, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 217, 300, 58));

        txtTipoCocina.setBackground(new java.awt.Color(212, 199, 199));
        txtTipoCocina.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtTipoCocina.setBorder(null);
        txtTipoCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoCocinaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 217, 277, 58));

        txtTiempo.setBackground(new java.awt.Color(212, 199, 199));
        txtTiempo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtTiempo.setBorder(null);
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1257, 217, 222, 58));

        tblPlatillos.setBackground(new java.awt.Color(212, 199, 199));
        tblPlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Nombre", "Ingredientes"
            }
        ));
        jScrollPane1.setViewportView(tblPlatillos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 1210, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPlatillos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngredienteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredienteFActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void txtTipoCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoCocinaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlatillos;
    private javax.swing.JTextField txtIngredienteF;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtTipoCocina;
    // End of variables declaration//GEN-END:variables
}
