/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.isw.pruebassoftware.app.recetas.cocina.uc1;

/**
 *
 * @author Dell
 */
public class DlgPlatillosGuardados extends javax.swing.JDialog {

    /**
     * Creates new form DlgPlatillosGuardados
     */
    public DlgPlatillosGuardados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTiempo = new javax.swing.JTextField();
        txtIngrediente1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResultadoRecetas = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTiempo.setBackground(new java.awt.Color(211, 204, 192));
        txtTiempo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, 250, 60));

        txtIngrediente1.setBackground(new java.awt.Color(211, 204, 192));
        txtIngrediente1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtIngrediente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 180, 310, 60));

        tblResultadoRecetas.setBackground(new java.awt.Color(217, 217, 217));
        tblResultadoRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResultadoRecetas.setPreferredSize(new java.awt.Dimension(1338, 511));
        jScrollPane3.setViewportView(tblResultadoRecetas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 1400, 540));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/platillosGuardados.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtTipo1.setBackground(new java.awt.Color(211, 204, 192));
        txtTipo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 290, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPlatillosGuardados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPlatillosGuardados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPlatillosGuardados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPlatillosGuardados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPlatillosGuardados dialog = new DlgPlatillosGuardados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblResultadoRecetas;
    private javax.swing.JTextField txtIngrediente1;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtTipo1;
    // End of variables declaration//GEN-END:variables
}
